#!/usr/bin/env python3
import re
import sys
import webbrowser
import urllib.request

import bs4

def scrape_moves(game_id):
    url = 'https://www.littlegolem.net/jsp/game/game.jsp?gid=' + game_id
    r = urllib.request.urlopen(url).read()
    soup = bs4.BeautifulSoup(r, 'html.parser')
    for tag in soup.find(text=re.compile('Move List')).find_parent(class_='portlet').find_all('b'):
        yield str(tag.string).split('.')[-1]

def swap_move(move):
    a, b = ord(move[0]) - ord('a'), int(move[1:]) - 1
    return chr(b + ord('a')) + str(a + 1)

if __name__ == '__main__':
    if len(sys.argv) != 2:
        print('usage: {} [Little Golem Game ID]'.format(sys.argv[0]), file=sys.stderr)
        sys.exit(1)
    moves = []
    for move in scrape_moves(sys.argv[1]):
        if move == 'resign':
            pass
        elif move == 'swap':
            move = swap_move(moves[-1])
            moves = [move, move]
        else:
            moves.append(move)
    webbrowser.open('http://trmph.com/hex/board#13,' + ''.join(moves))
